mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect

from django.urls import path


from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    logout_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    HelloView,
)

app_name = "myauth"





urlpatterns = [
    path("hello/", HelloView.as_view(), name="hello"),
    # path("", login_view, name="login"),  # Главная страница приложения

    path("register/", RegisterView.as_view(), name="register"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("logout/", logout_view, name="logout"),
    path("logout/", MyLogoutView.as_view, name="logout"),
    path("login/", LoginView.as_view(template_name="myauth/login.html",redirect_authenticated_user=True,), name="login"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view , name="session-get"),
    path("session/set/",  set_session_view, name="session-set"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar")
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView,SpectacularRedocView, SpectacularSwaggerView




urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name ="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'),name='redoc'),
    path('api/', include('myapiapp.urls')),

]

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
  path('shop/', include('shopapp.urls')),
)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from django.db import router
from django.urls import path,include
from rest_framework.routers import DefaultRouter
from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrderDetailView,
    create_product,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    ProductViewSet,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products",ProductViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("groups/",GroupsListView.as_view(), name="groups_list"),
    path("products/",ProductsListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(),name = "products_export"),  # Здесь имя маршрута "products_export"
    path("products/create",  ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/",ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/confirm-delete/",ProductDeleteView.as_view(), name="product_delete"),
    path("products/create/", create_product, name="product_create"),
    path("orders/",  OrdersListView.as_view(), name="orders_list"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),

]

mysite/shopapp/models.py
from django.db import models
from django.contrib.auth.models import User

def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preivew/{filename}".format(
        pk =instance.pk,
        filename=filename,
    )



class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продавать в интернет-магазине.

    Заказы тут: :model:`shopapp.Order`
    """

    class Meta:
        ordering = ["name", "price"]
        # verbose_name = _("Product")
        # db_table = "tech_product"
        # verbose_name_plural = "products"

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    arhived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to="product_preview_directory_path")

    # @property
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + "..."

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"

def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{}/images/{}".format(
        instance.product.pk, filename
    )



class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False,blank=True)

class Order(models.Model):
    delivery_address = models.TextField( null=True, blank=True)
    promocode = models.CharField(max_length=20, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True,upload_to='orders/receipts/')

mysite/shopapp/forms.py
from django import forms
from .models import Product
from django. forms import ModelForm
from django.contrib.auth.models import Group




class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount"


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name"]

mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view интернет-магазина: по товарам, заказам и т.д.
"""
from timeit import default_timer

import logging
from django.contrib.admindocs.views import ViewIndexView
from django.contrib.auth.models import Group
from django.contrib.messages import success
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import  LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from .forms import ProductForm , GroupForm
from .models import Product, Order
from rest_framework.viewsets import ModelViewSet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views import View
from timeit import default_timer
from .serializers import ProductSerializer
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse


log = logging.getLogger(__name__)


@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    набор представлений для действий для Product
    Полный CRUD сущностей товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields =[
        "name",
        "description",
        "price",
        "discount",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @extend_schema(
        summary="Get one product by ID",
        description="Retrieves **product**, returns 404 if not found",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Empty response, product by id not found"),
        }
    )
    def retrieve(self,  *args, **kwargs):
        return super().retrieve(*args,**kwargs)

class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
            "items": 1,
        }
        log.debug("Products for shop index: %s", products)
        log.info("Rendering shop index")
        return render(request, 'shopapp/shop-index.html', context=context)

class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request:HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)

class ProductDetailsView(DetailView):
    template_name = "shopapp/products-details.html"
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    context_object_name = "product"




class ProductsListView(ListView):
    template_name = "shopapp/products-list.html"
    model = Product
    context_object_name = "products"
    # queryset = Product.objects.filter(archived=False)

class ProductCreateView(UserPassesTestMixin,CreateView):
    def test_func(self):
        return self.request.user.groups.filter(name="secret-group").exists()
        # return self.request.user.is_superuser

    model = Product
    fields = "namme", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products_list")

class  ProductUpdateView(UpdateView):
    model = Product
    fields = "name", "price", "description", "discount", "preview"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    # def form_valid(self, form):
    #     success_url =self.get_success_url()
    #     # self.object.archived = True
    #     self.object.save()
    #     return HttpResponseRedirect(success_url)




class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
        .all()
    )

class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )





class ProductsDataExportView(View):
    def get(self, request):
        # Получаем все продукты, сортируя их по первичному ключу
        products = Product.objects.order_by("pk").all()

        # Создаем список данных о каждом продукте
        products_data = [
            {
                "pk": product.pk,  # ID продукта
                "name": product.name,  # Название продукта
                "price": float(product.price),  # Преобразуем цену в тип float
            }
            for product in products
        ]

        # Возвращаем данные в формате JSON
        return JsonResponse({"products": products_data})


# Ensure this import is correct and the form exists

def create_product(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            # name = form.cleaned_data["name"]
            # Product.objects.create(**form.cleaned_data)
            form.save()
            url = reverse("shopapp:products_list")  # Исправлено
            return redirect(url)
    else:
         form = ProductForm()  # Initialize the form
    context = {
        "form": form,
    }
    return render(request, "shopapp/create-product.html", context=context)

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        Base Title
      {% endblock %}
    </title>
</head>
<body>
{% block body %}
    Base body
{% endblock %}

<!--<div>-->
<!--   {% now 'H:i' %}-->
<!--</div>-->
<!--<div>-->

<!--   {% now 'l' as current_weekday %}-->
<!--  Today is {{ current_weekday }}-->
<!--</div>-->
</body>
</html>

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
      <form method="post">
         {% csrf_token %}

          {{form.as_p}}

          <button type="submit">
              Create
          </button>
      </form>
    </div>
<div>
    <a href="{% url 'shopapp:products_list' %}"
    >Back to products list</a>
</div>

{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Group List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Create</button>
    </form>
</div>
  <div>
    {% if not groups %}
        <h3>No groups yet</h3>
    {% else %}
        <ul>
            {% for group in groups %}
                <li>
                  <div>{{ group.name }}</div>
                  <ul>
                    {% for permission in group.permissions.all %}
                    <li>
                      {{permission.name }}
                      (<code>{{ permission.codename  }}</code>)
                    </li>

                    {% endfor %}
                  </ul>

                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order #{{ object.pk }} details
{% endblock %}

{% block body %}
<h1>Order #{{ object.pk }}</h1>
<div>
  <p>Order by {% firstof object.user.first_name object.user.username %}</p>
  <p>Promocode: <code>{{ object.promocode }}</code></p>
  <p>Delivery address: {{ object.delivery_address }}</p>
  <div>
    <p>Products in order:</p>
    <ul>
      {% for product in object.products.all %}
        <li>{{ product.name }} for ${{ product.price }}</li>
      {% endfor %}
    </ul>
  </div>
</div>
<div>
  <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
</div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>

  {% if object_list %}
    <div>
      {% for order in object_list %}
        <div>
        <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
        >Details #{{ order.pk }}</a></p>

          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>
            <p>Products in order:</p>
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}

{% endblock %}

mysite/shopapp/templates/shopapp/orders-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>

  {% if orders %}
    <div>
      {% for order in orders %}
        <div>
          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>
            <p>Products in order:</p>
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}

{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
<h1>Are you sure you want to delete{{object.name}}?</h1>
 <br>
 <div>
    <a href="{% url 'shopapp:product_details' pk=object.pk %}"
    >Back to product</a>
 </div>
 <br>
<div>
    <form method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button type="submit">Delete</button>
    </form>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create product</h1>
<div>
    <from method="post" enctype="multipart/form-data"></from>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Create</button>
    </form>
</div>
<div>
    <a href="{% url 'shopapp:products_list' %}"
    >Back to products list</a>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update product
{% endblock %}

{% block body %}
  <h1>Update product</h1>
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Update</button>
    </form>
</div>
<div>


    <a href="{% url 'shopapp:product_details' pk=object.pk %}"
    >Back to products list #{{ object.pk }} </a>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Products #{{ product.pk }}
{% endblock %}

{% block body %}
<h1>Product <strong>{{ product.name }}</strong></h1>
<div>
    <div>Description: <em>{{ product.description }}</em></div>
    <div>Price: {{ product.price }}</div>
    <div>Discount: {{ product.discount }}</div>
    <div>Archived: {{ product.archived }}</div>

    {% if product.preview %}
    <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
    {% endif %}

    <h3>Images:</h3>
    <div>
        {% for img in product.images.all %}
        <div>
            <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
            <div>{{ img.description }}</div>
        </div>
        {% empty %}
        <div>images uploded yet</div>
        {% endfor %}
    </div>



</div>
<div>
    <a href="{% url 'shopapp:product_update' product.pk %}">Update product</a>
</div>

<div>
    <a href="{% url 'shopapp:product_delete' product.pk %}">Delete product</a>
</div>

<div>
    <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
</div>

{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Products list' %}
{% endblock %}

{% block body %}
  <h1>{% translate 'Products' %}:</h1>

  {% if products %}
    <div>
      {% blocktrans count products_count=products|length %}
        There is one product.
      {% plural %}
        There are {{ products_count }} products.
      {% endblocktrans %}
    </div>

    <div>
      {% for product in products %}
        <div>
          <p>
            <a href="{% url 'shopapp:product_details' product.pk %}">
              {% translate 'Name' context 'product name' %}: {{ product.name }}
            </a>
          </p>
          <p>{% translate 'Price' %}: {{ product.price }}</p>
          {% translate 'no discount' as no_discount %}
          <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>

          {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
          {% endif %}
        </div>
      {% endfor %}
    </div>
    <div>
      <a href="{% url 'shopapp:product_create' %}">
        {% translate 'Create a new product' %}
      </a>
    </div>
  {% else %}
    {% url 'shopapp:product_create' as create_product_url %}
    {% blocktranslate %}
      <h3>No products yet</h3>
      <a href="{{ create_product_url }}">Create a new one</a>
    {% endblocktranslate %}
  {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Shop Index
{% endblock %}

{% block body %}
<h1>Hello Shop Index!</h1>

<div>
    <ul>
        {% for name, price in products %}
        <li>{{ name }} for ${{ price }}</li>
        {% if name|length == 7 %}
          <span>Lucky product</span>
        {% endif %}
        {% empty %}
        <li>No products here</li>
        {% endfor %}
    </ul>
</div>
<div>
    <strong>
      You have {{ items }} cherr{{items|pluralize:"y,ies"}}
    </strong>
</div>


 <div>Time running: {{ time_running }}</div>

 <div>
    {% lorem 3 p random %}
 </div>
{% endblock %}